name: Pylint
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint discord.py python-dotenv

    - name: Get changed Python files
      id: changed-files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || echo "No Python files changed."

    - name: Skip checks if no Python files changed
      if: steps.changed-files.outputs.result == ''
      run: echo "No Python files changed. Skipping Pylint checks." && exit 0

    - name: Run Pylint on changed files
      run: |
        echo "${{ steps.changed-files.outputs.result }}" | xargs pylint --rcfile=.pylintrc --disable=convention
